@startuml
title クラス図

class fileOperater
{
    fileName: string
    filePath: string
    setFilePath()
    getFilePath()
    createFile()
    saveFile()
}

abstract class fileReader
{
    readContents()
    getContents()
}

abstract class fileWriter
{
    writeContents()
}

fileOperater --> fileReader
fileOperater --> fileWriter

class csvReader
{
    readContents()
    getContents()
}

class csvWriter
{
    writeContents()
}

class tagFileReader
{
    readContents()
    getContents()
}

class tagFileWriter
{
    currentTagFile: string
    writeContents()
}

class imageReader
{
    imageFileNames: List<string>
    currentImage: image
    currentImageName: string
    currentImageIndex: int
    addImages()
    setCurrentImageInfo()
    getCurrentImageInfo()
    drawImage()
    drawZoomImage()
}

fileOperater --> imageReader

class imageDirectoryReader
{
    currentDirectory: string
    setDirectory()
    getDirectory()
    drawCurrentDirectory()
}

class tagOperator
{
    tags: List<string>
    tagFileReader: tagFileReader
    tagFileWriter: tagFileWriter
    addTag()
    removeTag()
}

class position
{
    x: int
    y: int
    setPosition()
    getPosition()
    getCurrentMousePosition()
    drawPosition()
}

class region
{
    leftTopPosition: position
    rightBottomPosition: position
    regions: List<List<position>>
    addRegion()
    removeRegion()
    getClickRegion()
    drawRegion()
}

fileReader --|> csvReader
fileReader --|> tagFileReader
fileWriter --|> csvWriter
fileWriter --|> tagFileWriter

@enduml